
// Generated by Selenium IDE
import java.util.HashMap;
import java.util.Map;

import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

public class Testcase1Test {
	private WebDriver driver;
	private Map<String, Object> vars;
	JavascriptExecutor js;

	
	public void setUp() {
		driver = new ChromeDriver();
		js = (JavascriptExecutor) driver;
		vars = new HashMap<String, Object>();
	}

	@After
	public void tearDown() {
		driver.quit();
	}

	@Test
	public void testcase1() {
		driver.get("https://www.facebook.com/r.php?locale=en_GB&display=page%22");
		driver.manage().window().setSize(new Dimension(1684, 901));
		driver.findElement(By.id("u_0_b_vi")).click();
		driver.findElement(By.id("u_0_b_vi")).sendKeys("Muthu");
		driver.findElement(By.id("u_0_d_pI")).click();
		driver.findElement(By.id("u_0_d_pI")).sendKeys("Varma");
		driver.findElement(By.id("day")).click();
		{
			WebElement dropdown = driver.findElement(By.id("day"));
			dropdown.findElement(By.xpath("//option[. = '1']")).click();
		}
		driver.findElement(By.id("u_0_4_lH")).click();
	}
}
